### ISSUE TITLE
Errors while loading native tdlight-java libraries on Ubuntu 16.04.7 LTS

### ISSUE THREAD

**Issue by ashvydkyi** [tdlight-team/tdlight-java#10]
hey guys

Can you please assist with the following error: 
```
Caused by: java.lang.UnsatisfiedLinkError: ../.tdlight-libs-cache/version-3.168.13/tdjni/tdjni.so: libssl.so.1.1: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
	at java.base/java.lang.Runtime.load0(Runtime.java:745)
	at java.base/java.lang.System.load(System.java:1871)
	at it.tdlight.tdlight.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:134)
	at it.tdlight.tdlight.utils.LoadLibrary.loadLibrary(LoadLibrary.java:80)
	... 61 common frames omitted
```

```
        <dependency>
            <groupId>it.tdlight</groupId>
            <artifactId>tdlight-java</artifactId>
            <version>3.168.13</version>
        </dependency>
```

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```

Regards,

Anton

**Comment by Cavallium** [comment]
You must have openssl >= 1.1 installed in your system.
Ubuntu 16.04 is too old, it has an older version: you must install the latest openssl version.

**Comment by ashvydkyi** [comment]
@Cavallium but why it is working with ?
```
<dependency>-->
   <groupId>it.tdlight</groupId>-->
   <artifactId>tdlib-java</artifactId>-->
   <version>3.168.13</version>-->
</dependency>-->
```

**Comment by anandundavia** [comment]
I have the same issue on Ubuntu 22.04

**Comment by anandundavia** [comment]
![image](https://user-images.githubusercontent.com/10672222/185737477-10c01f4d-caef-411d-b22b-d478a67cf967.png)

**Comment by cavallium** [comment]
you must install libssl

**Comment by anandundavia** [comment]
I already have it 

![image](https://user-images.githubusercontent.com/10672222/185737975-d768e760-4b74-429c-90d2-382d2d3fd49a.png)

**Comment by anandundavia** [comment]
This answer helped - https://askubuntu.com/a/1102966/683621
