### ISSUE TITLE
Cannot use with Java 8

### ISSUE THREAD

**Issue by morfeusys** [tdlight-team/tdlight-java#125]
README promises that tdlight-java can be used with Java 8, but I get

`Exception in thread "main" java.lang.UnsupportedClassVersionError: it/tdlight/jni/TdApi$Function has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

when trying to use

```
dependencies {
    implementation(kotlin("stdlib"))

    implementation(platform("it.tdlight:tdlight-java-bom:2.8.8.2"))
    api("it.tdlight:tdlight-java")
    implementation("it.tdlight:tdlight-natives-osx-amd64")
}

tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    compileTestKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
}
```

**Comment by chuprynink** [comment]
same problem

**Comment by cavallium** [comment]
Can you print the computed dependency tree?

**Comment by chuprynink** [comment]
> Can you print the computed dependency tree?

[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< ru.org.chk:test >---------------------------
[INFO] Building test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ test ---
[INFO] ru.org.chk:test:jar:1.0-SNAPSHOT
[INFO] +- it.tdlight:tdlight-java:jar:2.8.8.1:compile
[INFO] |  +- it.tdlight:tdlight-api-sealed:jar:4.0.280:compile
[INFO] |  +- it.unimi.dsi:fastutil:jar:8.5.9:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:2.0.3:compile
[INFO] |  +- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO] |  +- net.harawata:appdirs:jar:1.2.1:compile
[INFO] |  |  \- net.java.dev.jna:jna-platform:jar:5.6.0:compile
[INFO] |  |     \- net.java.dev.jna:jna:jar:5.6.0:compile
[INFO] |  \- com.google.zxing:core:jar:3.5.0:compile
[INFO] \- it.tdlight:tdlight-natives-windows-amd64:jar:4.0.282:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.672 s
[INFO] Finished at: 2022-12-03T21:52:50+03:00
[INFO] ------------------------------------------------------------------------

Exception in thread "main" java.lang.UnsupportedClassVersionError: it/tdlight/jni/TdApi has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at jdk.nashorn.internal.runtime.Context.findClass(Context.java:1051)
	at jdk.nashorn.internal.runtime.NativeJavaPackage.createProperty(NativeJavaPackage.java:232)
	at jdk.nashorn.internal.runtime.NativeJavaPackage.noSuchProperty(NativeJavaPackage.java:204)
	at jdk.nashorn.internal.runtime.ScriptObject.findGetMethod(ScriptObject.java:1952)
	at jdk.nashorn.internal.runtime.ScriptObject.lookup(ScriptObject.java:1820)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:104)
	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
	at jdk.nashorn.internal.scripts.Script$9$chktgclient_jjs.:program(chktgclient.jjs:5)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.tools.Shell.apply(Shell.java:471)
	at jdk.nashorn.tools.Shell.runScripts(Shell.java:400)
	at jdk.nashorn.tools.Shell.run(Shell.java:179)
	at jdk.nashorn.tools.Shell.main(Shell.java:143)
	at jdk.nashorn.tools.Shell.main(Shell.java:119)

**Comment by cavallium** [comment]
> it.tdlight:tdlight-api-sealed:jar:4.0.280:compile

It seems that gradle is choosing the sealed version of tdlight (java 17+): it.tdlight:tdlight-api-sealed:jar:4.0.280:compile
What is your default JVM installed? is your java_home pointing to java 8?

**Comment by cavallium** [comment]
I added a new package for Java 8+, please try the latest version and use `tdlight-java-8` instead of `tdlight-java`

**Comment by morfeusys** [comment]
@cavallium thanks!! works now
