### ISSUE TITLE
GLIBC_2.28 not found

### ISSUE THREAD

**Issue by mustafin** [tdlight-team/tdlight-java#130]
```
stack_trace: java.lang.ExceptionInInitializerError: null
Caused by: it.tdlight.common.utils.CantLoadLibrary: Init failed when loading TDLib native libraries, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:93)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:71)
	at it.tdlight.common.Init.start(Init.java:50)
	at ru.yandex.vertis.basebot.components.processors.td.TdLibUpdatesProcessor.<init>(TdLibUpdatesProcessor.scala:36)
	at ru.yandex.vertis.basebot.workers.WorkersSupport$$anon$39.<init>(WorkersSupport.scala:241)
	at ru.yandex.vertis.basebot.workers.WorkersSupport.$init$(WorkersSupport.scala:241)
	at ru.yandex.vertis.basebot.components.SchedulerComponents.<init>(SchedulerComponents.scala:33)
	at ru.yandex.vertis.basebot.Launcher.$init$(Launcher.scala:13)
	at ru.yandex.vertis.basebot.Main$.<clinit>(Main.scala:5)
	... 1 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /.cache/version-tdlight-2.8.10.2-4.0.293/tdjni/tdjni.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /.cache/version-tdlight-2.8.10.2-4.0.293/tdjni/tdjni.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:192)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:88)
	... 9 common frames omitted
	
```

I use ubuntu 16.04

**Comment by cavallium** [comment]
Ubuntu 16 is not supported.
