### ISSUE TITLE
libssl.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by imyoric** [tdlight-team/tdlight-java#146]
[https://github.com/tdlight-team/tdlight-java/issues/10](#10)- Not helped. 

```
/usr/lib/jvm/java-17-openjdk-amd64/bin/java -Dfile.encoding=UTF-8 -classpath /root/TGAuto1/sIbfbuJ8he:/root/TGAuto1/83QNxSxF9h/slf4j-reload4j-2.0.5.jar:/root/TGAuto1/3XkcPqyYy9/slf4j-api-2.0.5.jar:/root/TGAuto1/5p1mDRQ3DC/reload4j-1.2.22.jar:/root/TGAuto1/xzDkJy41aI/tdlight-natives-linux-amd64-4.0.299-ssl3.jar:/root/TGAuto1/X6ujyR5xbD/tdlight-java-2.8.10.6-ssl3.jar:/root/TGAuto1/dS0JwEoEb7/tdlight-api-sealed-4.0.297.jar:/root/TGAuto1/eXN4Ss7cpj/reactive-streams-1.0.4.jar ru.yoricya.tgauto.Main
Exception in thread "main" it.tdlight.common.utils.CantLoadLibrary: Init failed when loading TDLib native libraries, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:93)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:71)
	at it.tdlight.common.Init.start(Init.java:50)
	at ru.yoricya.tgauto.Main.main(Main.java:35)
Caused by: java.lang.UnsatisfiedLinkError: /root/TGAuto1/FLMBnRG11c/.cache/version-tdlight-2.8.10.6-ssl3-4.0.299/tdjni/tdjni.so: libssl.so.3: невозможно открыть разделяемый объектный файл: Нет такого файла или каталога
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:192)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:88)
	... 3 more

Process finished with exit code 1

```
System: Debian 11 by OpenMediaVault
libssl - Installed by sudo apt-get install libssl-dev
openssl - installed by sudo apt-get install openssl
Please Help)

**Comment by cavallium** [comment]
Do not use the -ssl3 version

**Comment by imyoric** [comment]
> Do not use the -ssl3 version

Thanks
