### ISSUE TITLE
Starting application from JAR

### ISSUE THREAD

**Issue by yvasyliev** [tdlight-team/tdlight-java#15]
Hi, I have a problem with starting application from a JAR:
`java -jar TgClient-1.0-SNAPSHOT.jar`
<pre>Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: it/tdlight/jni/TdApi$Function
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: it.tdlight.jni.TdApi$Function
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more</pre>

I am able to start the application inside Intellij Idea without any problems. 
Could you please help me with that? 
Thanks

**Comment by Cavallium** [comment]
How are you building your .jar? Can you send me it?

**Comment by yvasyliev** [comment]
I just realized that I was building JAR without dependencies... Now it's ok. Sorry for disturb.
