### ISSUE TITLE
Example.java - Failed to load TDLight native libraries

### ISSUE THREAD

**Issue by aravorn6** [tdlight-team/tdlight-java#154]
The example is not working on linux
The workdir /tmp/tdlight-java-natives4385709636704884643 is empty  

`2023-05-17 18:04:54.231 [32;1mDEBUG[m [35m16316[m [36mNativeLibraryLoader [m : -Dit.tdlight.native.workdir: /tmp/tdlight-java-natives4385709636704884643 (it.tdlight.tmpdir)
2023-05-17 18:04:54.233 [32;1mDEBUG[m [35m16316[m [36mNativeLibraryLoader [m : -Dit.tdlight.native.deleteLibAfterLoading: true
2023-05-17 18:04:54.234 [32;1mDEBUG[m [35m16316[m [36mNativeLibraryLoader [m : -Dit.tdlight.native.tryPatchShadedId: true
2023-05-17 18:04:54.234 [32;1mDEBUG[m [35m16316[m [36mNativeLibraryLoader [m : -Dit.tdlight.native.detectNativeLibraryDuplicates: true
Exception in thread "main" it.tdlight.util.UnsupportedNativeLibraryException: Failed to load TDLight native libraries
	at it.tdlight.util.Native.loadLibrary(Native.java:62)
	at it.tdlight.util.Native.loadNativesInternal(Native.java:37)
	at it.tdlight.Init.init(Init.java:53)
	at telegram.Example.main(Example.java:33)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [tdjni.linux_amd64_ssl1, tdjni.linux_amd64_ssl3]
	at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:130)
	at it.tdlight.util.Native.loadLibrary(Native.java:55)`

**Comment by cavallium** [comment]
Please, can you copy the full exception?
Also, keep the formatting, it's almost unreadable

**Comment by aravorn6** [comment]
[exception.txt](https://github.com/tdlight-team/tdlight-java/files/11506230/exception.txt)

Exception in thread "main" it.tdlight.util.UnsupportedNativeLibraryException: Failed to load TDLight native libraries
	at it.tdlight.util.Native.loadLibrary(Native.java:62)
	at it.tdlight.util.Native.loadNativesInternal(Native.java:37)
	at it.tdlight.Init.init(Init.java:53)
	at telegram.Example.main(Example.java:33)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [tdjni.linux_amd64_ssl1, tdjni.linux_amd64_ssl3]
	at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:130)
	at it.tdlight.util.Native.loadLibrary(Native.java:55)
	... 3 more
	Suppressed: java.lang.UnsatisfiedLinkError: /tmp/tdlight-java-natives10846564413041546263/libtdjni.linux_amd64_ssl18270579528693625650.so: libc++.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
		at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
		at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
		at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
		at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
		at java.base/java.lang.Runtime.load0(Runtime.java:755)
		at java.base/java.lang.System.load(System.java:1953)
		at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:21)
		at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:433)
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:234)
		at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:121)
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: /tmp/tdlight-java-natives10846564413041546263/libtdjni.linux_amd64_ssl18270579528693625650.so: libc++.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
			at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
			at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
			at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
			at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
			at java.base/java.lang.Runtime.load0(Runtime.java:755)
			at java.base/java.lang.System.load(System.java:1953)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:21)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:568)
			at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:462)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:425)
			... 6 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl1 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:433)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177)
			... 5 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl1 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:462)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:425)
				... 6 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni.linux_amd64_ssl3
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:255)
		at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:121)
		... 4 more
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/libtdjni.linux_amd64_ssl3.so
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:202)
		... 5 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:433)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177)
			... 5 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl3 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:462)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:425)
				... 6 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:255)
		at it.tdlight.util.Native.loadLibrary(Native.java:58)
		... 3 more
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/libtdjni.so
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:202)
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
			at java.base/java.lang.System.loadLibrary(System.java:1989)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:433)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177)
			... 4 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
				at java.base/java.lang.System.loadLibrary(System.java:1989)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:568)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:462)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:425)
				... 5 more

**Comment by aravorn6** [comment]
this method throws the exception. method.invoke(null, name, absolute); The file is in the workdir 	


          private static void loadLibraryByHelper(final Class<?> helper, final String name, final boolean absolute)
			throws UnsatisfiedLinkError {

		Object ret;
		try {
			// Invoke the helper to load the native library, if succeed, then the native
			// library belong to the specified ClassLoader.
			Method method = helper.getMethod("loadLibrary", String.class, boolean.class);
			method.setAccessible(true);
			ret = method.invoke(null, name, absolute);
		} catch (Exception e) {
			ret = e;
		}
		if (ret instanceof Throwable) {
			Throwable t = (Throwable) ret;
			assert !(t instanceof UnsatisfiedLinkError) : t + " should be a wrapper throwable";
			Throwable cause = t.getCause();
			if (cause instanceof UnsatisfiedLinkError) {
				throw (UnsatisfiedLinkError) cause;
			}
			UnsatisfiedLinkError ule = new UnsatisfiedLinkError(t.getMessage());
			ule.initCause(t);
			throw ule;
		}
	}

**Comment by cavallium** [comment]
"libc++.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden"

You should install libc++

**Comment by aravorn6** [comment]
I find this library on my distribution and now it works
