### ISSUE TITLE
Failed to load TDLight native libraries

### ISSUE THREAD

**Issue by alon-sys** [tdlight-team/tdlight-java#158]
version：3.0.9+td.1.8.14
OS：Centos 8

it.tdlight.util.UnsupportedNativeLibraryException: Failed to load TDLight native libraries
	at it.tdlight.util.Native.loadLibrary(Native.java:62)
	at it.tdlight.util.Native.loadNativesInternal(Native.java:37)
	at it.tdlight.Init.init(Init.java:53)
	at com.tgsys.controller.TgClientLoginController.lambda$startHandler$0(TgClientLoginController.java:61)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [tdjni.linux_amd64_ssl1, tdjni.linux_amd64_ssl3]
	at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:132)
	at it.tdlight.util.Native.loadLibrary(Native.java:55)
	... 8 more
	Suppressed: java.lang.UnsatisfiedLinkError: /tmp/tdlight-java-natives8998926089843329338/libtdjni.linux_amd64_ssl113133838849942033131.so: libc++.so.1: cannot open shared object file: No such file or directory
		at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
		at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2432)
		at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2489)
		at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2689)
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2619)
		at java.base/java.lang.Runtime.load0(Runtime.java:765)
		at java.base/java.lang.System.load(System.java:1835)
		at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:21)
		at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:439)
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:236)
		at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:123)
		... 9 more
		Suppressed: java.lang.UnsatisfiedLinkError: /tmp/tdlight-java-natives8998926089843329338/libtdjni.linux_amd64_ssl113133838849942033131.so: libc++.so.1: cannot open shared object file: No such file or directory
			at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
			at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2432)
			at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2489)
			at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2689)
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2619)
			at java.base/java.lang.Runtime.load0(Runtime.java:765)
			at java.base/java.lang.System.load(System.java:1835)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:21)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:566)
			at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:468)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:431)
			... 11 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl1 in java.library.path: [/usr/local/bin]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
			at java.base/java.lang.System.loadLibrary(System.java:1871)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:439)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:179)
			... 10 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl1 in java.library.path: [/usr/local/bin]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
				at java.base/java.lang.System.loadLibrary(System.java:1871)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:468)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:431)
				... 11 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni.linux_amd64_ssl3
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:257)
		at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:123)
		... 9 more
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/libtdjni.linux_amd64_ssl3.so
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:204)
		... 10 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl3 in java.library.path: [/usr/local/bin]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
			at java.base/java.lang.System.loadLibrary(System.java:1871)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:439)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:179)
			... 10 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.linux_amd64_ssl3 in java.library.path: [/usr/local/bin]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
				at java.base/java.lang.System.loadLibrary(System.java:1871)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:468)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:431)
				... 11 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:257)
		at it.tdlight.util.Native.loadLibrary(Native.java:58)
		... 8 more
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/libtdjni.so
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:204)
		... 9 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: [/usr/local/bin]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
			at java.base/java.lang.System.loadLibrary(System.java:1871)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:439)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:179)
			... 9 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: [/usr/local/bin]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2662)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:827)
				at java.base/java.lang.System.loadLibrary(System.java:1871)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:468)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:431)
				... 10 more

**Comment by ristargomel** [comment]
I had same issue, you should install libc++
https://github.com/tdlight-team/tdlight-java/issues/154
