### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by dumbled00r** [tdlight-team/tdlight-java#159]
When i tried to run the example, i encounter this error (even with TDLib)

```
Exception in thread "main" it.tdlight.util.UnsupportedNativeLibraryException: Failed to load TDLight native libraries
	at it.tdlight.util.Native.loadLibrary(Native.java:62)
	at it.tdlight.util.Native.loadNativesInternal(Native.java:37)
	at it.tdlight.Init.init(Init.java:53)
	at it.tdlight.example.Example.main(Example.java:34)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [tdjni.windows_amd64]
	at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:130)
	at it.tdlight.util.Native.loadLibrary(Native.java:55)
	... 3 more
	Suppressed: java.lang.RuntimeException: java.nio.file.AccessDeniedException: C:\Users\PC\AppData\Local\Temp\tdlight-java-natives6579794564266726560\tdjni.windows_amd6417772113716526451840.dll
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:270)
		at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:121)
		... 4 more
	Caused by: java.nio.file.AccessDeniedException: C:\Users\PC\AppData\Local\Temp\tdlight-java-natives6579794564266726560\tdjni.windows_amd6417772113716526451840.dll
		at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
		at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
		at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:273)
		at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:109)
		at java.base/java.nio.file.Files.deleteIfExists(Files.java:1190)
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:266)
		... 5 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:255)
		at it.tdlight.util.Native.loadLibrary(Native.java:58)
		... 3 more
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/tdjni.dll
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:202)
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: C:\Program Files\Java\jdk-20\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_202\bin;C:\Maven\apache-maven-3.9.2\bin;C:\Program Files\CMake\bin;C:\php-8.2.6-nts-Win32-vs16-x64;C:\Program Files\OpenSSL-Win64\bin;C:\Users\PC\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\PC\AppData\Local\Programs\Python\Python311\;C:\Users\PC\AppData\Local\Microsoft\WindowsApps;C:\Users\PC\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\bin;;C:\php-8.2.6-nts-Win32-vs16-x64;C:\Program Files\OpenSSL-Win64\bin;;.
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:880)
			at java.base/java.lang.System.loadLibrary(System.java:2051)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:433)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:177)
			... 4 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: C:\Program Files\Java\jdk-20\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft MPI\Bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Azure Data Studio\bin;C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Git\cmd;C:\Program Files\Java\jdk1.8.0_202\bin;C:\Maven\apache-maven-3.9.2\bin;C:\Program Files\CMake\bin;C:\php-8.2.6-nts-Win32-vs16-x64;C:\Program Files\OpenSSL-Win64\bin;C:\Users\PC\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\PC\AppData\Local\Programs\Python\Python311\;C:\Users\PC\AppData\Local\Microsoft\WindowsApps;C:\Users\PC\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2023.1.2\bin;;C:\php-8.2.6-nts-Win32-vs16-x64;C:\Program Files\OpenSSL-Win64\bin;;.
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2444)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:880)
				at java.base/java.lang.System.loadLibrary(System.java:2051)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
				at java.base/java.lang.reflect.Method.invoke(Method.java:578)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:462)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:425)
				... 5 more
```

How to fix :(, I've been searching for a solution for the whole week

**Comment by cavallium** [comment]
Please update to the latest version, it has already been fixed
