### ISSUE TITLE
Init failled when load tdlib library, execution can't continue

### ISSUE THREAD

**Issue by kimnamcham** [tdlight-team/tdlight-java#18]
When i run project in mac os 64 bit, it's throw exception:

> Exception in thread "main" it.tdlight.common.utils.CantLoadLibrary: FATAL: Init failled when load tdlib library, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:87)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:65)
	at it.tdlight.common.Init.start(Init.java:44)
	at Example.main(Example.java:307)
Caused by: java.io.IOException: Native libraries for platform osx-amd64 not found!
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:150)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:82)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:148)
	... 4 more
Caused by: java.lang.NoSuchMethodError: java.lang.Class.getPackageName()Ljava/lang/String;
	at it.tdlight.jni.tdlight.osx.amd64.LoadLibrary.getOsName(LoadLibrary.java:13)
	at it.tdlight.jni.tdlight.osx.amd64.LoadLibrary.getLibraryAsStream(LoadLibrary.java:9)
	... 9 more

**Comment by Cavallium** [comment]
What version are you using?

**Comment by Cavallium** [comment]
I fixed it in the latest release: 3.169.113

**Comment by imyoric** [comment]
> I fixed it in the latest release: 3.169.113

But the latest version is 2.8.10.6
