### ISSUE TITLE
Fail to load chats

### ISSUE THREAD

**Issue by jcai** [tdlight-team/tdlight-java#184]
`17:49:25.074 [TDLib thread] WARN it.tdlight.client.AuthorizationStateReadyLoadChats - Failed to execute TdApi.LoadChats()`

If I ignore the warn message and send message ,chat not found 

```
it.tdlight.client.TelegramError: 400: Chat not found
        at it.tdlight.client.SimpleTelegramClient.lambda$sendUnsafe$5(SimpleTelegramClient.java:377)
        at it.tdlight.InternalClient.handleResponse(InternalClient.java:99)
        at it.tdlight.InternalClient.handleEvent(InternalClient.java:117)
        at it.tdlight.InternalClient.handleEvents(InternalClient.java:71)
        at it.tdlight.ClientFactoryImpl.handleClientEvents(ClientFactoryImpl.java:87)
        at it.tdlight.ResponseReceiver.run(ResponseReceiver.java:113)
```

code is :

```
				TdApi.User me = app.getClient().getMeAsync().get(1, TimeUnit.MINUTES);

				// Send a test message
				SendMessage req = new SendMessage();
				req.chatId = me.id;
				InputMessageText txt = new InputMessageText();
				txt.text = new FormattedText("TDLight test", new TextEntity[0]);
				req.inputMessageContent = txt;
				Message result = app.getClient().sendMessage(req, true).get(1, TimeUnit.MINUTES);
				System.out.println("Sent message:" + result);
```

**Comment by cavallium** [comment]
is this a bot or a user?

**Comment by JavoxirJava** [comment]
I have the same problem

**Comment by cavallium** [comment]
> I have the same problem

Is it a bot or a user?

**Comment by chjrco** [comment]
I encountered the same problem, creating a user. Please help.

**Comment by zerorooot** [comment]
I don’t know what it is, but when I wait for a while, the app stops reporting errors.
```java
TdApi.User me = app.getClient().getMeAsync().get(1, TimeUnit.MINUTES);

SendMessage req = new SendMessage();
req.chatId = me.id;
InputMessageText txt = new InputMessageText();
txt.text = new FormattedText("TDLight test", new TextEntity[0]);
req.inputMessageContent = txt;
//sleep it
Thread.sleep(3000);
Message result = app.getClient().sendMessage(req, true).get(1, TimeUnit.MINUTES);
System.out.println("Sent message:" + result);
```
I log in using user
```java
SimpleAuthenticationSupplier<?> authenticationData = AuthenticationSupplier.user("1xxxxxxx");
```

**Comment by ShafiqSadat** [comment]
Client not fully close when call client.sendClose()

```
package org.example;

import it.tdlight.Init;
import it.tdlight.Log;
import it.tdlight.Slf4JLogMessageHandler;
import it.tdlight.client.*;
import it.tdlight.jni.TdApi;
import it.tdlight.jni.TdApi.AuthorizationState;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.concurrent.TimeUnit;

public final class SessionChecker {


    public static void checkSession(int APP_ID, String APP_HASH, String sessionName) throws Exception {

        Init.init();

        Log.setLogMessageHandler(1, new Slf4JLogMessageHandler());

            SimpleTelegramClientFactory clientFactory = new SimpleTelegramClientFactory();
            APIToken apiToken = new APIToken(APP_ID, APP_HASH);
            TDLibSettings settings = TDLibSettings.create(apiToken);
            Path sessionPath = Paths.get(sessionName);
            settings.setDatabaseDirectoryPath(sessionPath.resolve("data"));
            settings.setDownloadedFilesDirectoryPath(sessionPath.resolve("downloads"));

            SimpleTelegramClientBuilder clientBuilder = clientFactory.builder(settings);

            ConsoleInteractiveAuthenticationData authenticationData = AuthenticationSupplier.consoleLogin();
            SimpleTelegramClient client = clientBuilder.build(authenticationData);
            client.addUpdateHandler(TdApi.UpdateAuthorizationState.class, (update) -> {
                var ccc = onUpdateAuthorizationState(update, client);
                if (ccc.equals("Logged in")) {
                    System.out.println("Logged in");
                    try {
                        client.sendClose();
                        Thread.yield();
                    } catch (Exception e) {
                        throw new RuntimeException(e);
                    }
                }
            });
    }

    private static String onUpdateAuthorizationState(TdApi.UpdateAuthorizationState update, SimpleTelegramClient client) {
        AuthorizationState authorizationState = update.authorizationState;
        var status = "";
        if (authorizationState instanceof TdApi.AuthorizationStateReady) {
            status = "Logged in";
            try {
                client.sendClose();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        } else if (authorizationState instanceof TdApi.AuthorizationStateClosing) {
            System.out.println("Closing...");
            status = "Closing...";
        } else if (authorizationState instanceof TdApi.AuthorizationStateClosed) {
            System.out.println("Closed");
            status = "Closed";
        } else if (authorizationState instanceof TdApi.AuthorizationStateLoggingOut) {
            System.out.println("Logging out...");
            status = "Logging out...";
        } else if (authorizationState instanceof TdApi.AuthorizationStateWaitPhoneNumber) {
            System.out.println("WaitPhoneNumber");
            status = "WaitPhoneNumber";
            try {
                client.sendClose();
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
        return status;
    }
}
```

![image](https://github.com/tdlight-team/tdlight-java/assets/22668836/8ff15e50-9f77-47e7-b614-fdd484ece1b2)

**Comment by cavallium** [comment]
> `17:49:25.074 [TDLib thread] WARN it.tdlight.client.AuthorizationStateReadyLoadChats - Failed to execute TdApi.LoadChats()`
> 
> If I ignore the warn message and send message ,chat not found
> 
> ```
> it.tdlight.client.TelegramError: 400: Chat not found
>         at it.tdlight.client.SimpleTelegramClient.lambda$sendUnsafe$5(SimpleTelegramClient.java:377)
>         at it.tdlight.InternalClient.handleResponse(InternalClient.java:99)
>         at it.tdlight.InternalClient.handleEvent(InternalClient.java:117)
>         at it.tdlight.InternalClient.handleEvents(InternalClient.java:71)
>         at it.tdlight.ClientFactoryImpl.handleClientEvents(ClientFactoryImpl.java:87)
>         at it.tdlight.ResponseReceiver.run(ResponseReceiver.java:113)
> ```
> 
> code is :
> 
> ```
> 				TdApi.User me = app.getClient().getMeAsync().get(1, TimeUnit.MINUTES);
> 
> 				// Send a test message
> 				SendMessage req = new SendMessage();
> 				req.chatId = me.id;
> 				InputMessageText txt = new InputMessageText();
> 				txt.text = new FormattedText("TDLight test", new TextEntity[0]);
> 				req.inputMessageContent = txt;
> 				Message result = app.getClient().sendMessage(req, true).get(1, TimeUnit.MINUTES);
> 				System.out.println("Sent message:" + result);
> ```

Please look at the new example
