### ISSUE TITLE
Build TDLib natives for MacOS

### ISSUE THREAD

**Issue by ashvydkyi** [tdlight-team/tdlight-java#2]
As of now, Mac OS is not supported. Can somebody spend time and add it.

**Comment by Cavallium** [comment]
Unfortunately we can only build the native libraries for Linux, we don't have the time to build it for Mac OS.
I'll add the label "Help wanted" to this issue.

**Comment by Cavallium** [comment]
I added support for Mac OS in version [3.168.7](https://github.com/tdlight-team/tdlight-java/releases/tag/v3.168.7-tdlight)
Reopen this issue if it doesn't work because we don't have any Mac to test it.

**Comment by ashvydkyi** [comment]
hey @Cavallium 
thx for adding support for Mac OS

I've tested **tdlight-java** with 3.168.11 version and it works well, 
but when I tried **tdlib-java** with the same version 3.168.11
the following exception is thrown

```
FATAL ERROR in native method: RegisterNatives failed for nativeClientReceive with signature (J[J[Lit/tdlight/tdlib/TdApi$Object;DZZ)I
	at java.lang.ClassLoader$NativeLibrary.load0(java.base@14.0.2/Native Method)
	at java.lang.ClassLoader$NativeLibrary.load(java.base@14.0.2/ClassLoader.java:2452)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@14.0.2/ClassLoader.java:2508)
	- locked <0x0000000700432650> (a java.util.HashSet)
	at java.lang.ClassLoader.loadLibrary0(java.base@14.0.2/ClassLoader.java:2704)
	at java.lang.ClassLoader.loadLibrary(java.base@14.0.2/ClassLoader.java:2637)
	at java.lang.Runtime.load0(java.base@14.0.2/Runtime.java:745)
	at java.lang.System.load(java.base@14.0.2/System.java:1871)
	at it.tdlight.tdlight.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:134)
	at it.tdlight.tdlight.utils.LoadLibrary.loadLibrary(LoadLibrary.java:80)
	at it.tdlight.tdlight.utils.LoadLibrary.load(LoadLibrary.java:63)
	at it.tdlight.tdlight.Init.start(Init.java:46)
	- locked <0x00000007032c9558> (a java.lang.Class for it.tdlight.tdlight.Init)
	at it.tdlight.tdlight.Client.<init>(Client.java:31)
[ 1][t 0][1599679723.491142034][tl_jni_object.cpp:37]	RegisterNatives failed for nativeClientReceive with signature (J[J[Lit/tdlight/tdlib/TdApi$Object;DZZ)I
```

@Cavallium can you please take a look. I can assist with testing if needed. thx.

**Comment by Cavallium** [comment]
Did you delete the .JTDLibLibraries folder? It's a temporary folder that stores the extracted libraries.
When you change the tdlib/tdlight variant, the folder has the same libraries as before, so you need to delete it.
In the next update I'll make sure to differentiate the folder names to avoid such problems.

> FATAL ERROR in native method: RegisterNatives failed for nativeClientReceive with signature (J[J[Lit/tdlight/tdlib/TdApi$Object;DZZ)I

**Comment by msxfXF** [comment]
Hello, I need the same help. I use Mac M1, but it seems that there is only **macos_amd64** in the Maven?
I hope someone can help me compile **arm64 version**
