### ISSUE TITLE
Failed to load TDLight native libraries (which was built for Mac OS X 12.6)

### ISSUE THREAD

**Issue by imyoric** [tdlight-team/tdlight-java#205]
```
Exception in thread "main" java.lang.RuntimeException: it.tdlight.util.UnsupportedNativeLibraryException: Failed to load TDLight native libraries
	at ru.yoricya.tgsaver.Main.main(Main.java:250)
Caused by: it.tdlight.util.UnsupportedNativeLibraryException: Failed to load TDLight native libraries
	at it.tdlight.util.Native.loadLibrary(Native.java:65)
	at it.tdlight.util.Native.loadNativesInternal(Native.java:37)
	at it.tdlight.Init.init(Init.java:53)
	at ru.yoricya.tgsaver.Main.main(Main.java:248)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [tdjni.macos_amd64]
	at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:132)
	at it.tdlight.util.Native.loadLibrary(Native.java:55)
	... 3 more
	Suppressed: java.lang.UnsatisfiedLinkError: /private/var/folders/lf/rrgmz18j7tg1cwtjwg7zd96h0000gn/T/tdlight-java-natives8939417937170926151/libtdjni.macos_amd6414175265717579816506.dylib: dlopen(/private/var/folders/lf/rrgmz18j7tg1cwtjwg7zd96h0000gn/T/tdlight-java-natives8939417937170926151/libtdjni.macos_amd6414175265717579816506.dylib, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strERKNS_12basic_stringIcS2_S4_EE
  Referenced from: /private/var/folders/lf/rrgmz18j7tg1cwtjwg7zd96h0000gn/T/tdlight-java-natives8939417937170926151/libtdjni.macos_amd6414175265717579816506.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

		at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
		at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
		at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
		at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
		at java.base/java.lang.Runtime.load0(Runtime.java:852)
		at java.base/java.lang.System.load(System.java:2025)
		at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:21)
		at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:439)
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:236)
		at it.tdlight.util.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:123)
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: /private/var/folders/lf/rrgmz18j7tg1cwtjwg7zd96h0000gn/T/tdlight-java-natives8939417937170926151/libtdjni.macos_amd6414175265717579816506.dylib: dlopen(/private/var/folders/lf/rrgmz18j7tg1cwtjwg7zd96h0000gn/T/tdlight-java-natives8939417937170926151/libtdjni.macos_amd6414175265717579816506.dylib, 1): Symbol not found: __ZNSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strERKNS_12basic_stringIcS2_S4_EE
  Referenced from: /private/var/folders/lf/rrgmz18j7tg1cwtjwg7zd96h0000gn/T/tdlight-java-natives8939417937170926151/libtdjni.macos_amd6414175265717579816506.dylib (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

			at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
			at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
			at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
			at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
			at java.base/java.lang.Runtime.load0(Runtime.java:852)
			at java.base/java.lang.System.load(System.java:2025)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:21)
			at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
			at java.base/java.lang.reflect.Method.invoke(Method.java:580)
			at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:468)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:431)
			... 6 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.macos_amd64 in java.library.path: /Users/aroslav/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
			at java.base/java.lang.System.loadLibrary(System.java:2063)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:439)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:179)
			... 5 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni.macos_amd64 in java.library.path: /Users/aroslav/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
				at java.base/java.lang.System.loadLibrary(System.java:2063)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
				at java.base/java.lang.reflect.Method.invoke(Method.java:580)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:468)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:431)
				... 6 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: tdjni
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:257)
		at it.tdlight.util.Native.loadLibrary(Native.java:58)
		... 3 more
	Caused by: java.io.FileNotFoundException: META-INF/tdlightjni/libtdjni.dylib
		at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:204)
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: /Users/aroslav/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
			at java.base/java.lang.System.loadLibrary(System.java:2063)
			at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
			at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:439)
			at it.tdlight.util.NativeLibraryLoader.load(NativeLibraryLoader.java:179)
			... 4 more
			Suppressed: java.lang.UnsatisfiedLinkError: no tdjni in java.library.path: /Users/aroslav/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2458)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:916)
				at java.base/java.lang.System.loadLibrary(System.java:2063)
				at it.tdlight.util.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:23)
				at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
				at java.base/java.lang.reflect.Method.invoke(Method.java:580)
				at it.tdlight.util.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:468)
				at it.tdlight.util.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:431)
				... 5 more
```

Are there libraries for older versions of macos?

**Comment by cavallium** [comment]
no, please update your os

**Comment by imyoric** [comment]
Okay, but can I compile all the required libraries using macOS 11 myself?

**Comment by cavallium** [comment]
> Okay, but can I compile all the required libraries using macOS 11 myself?

Yes, it's open source
