### ISSUE TITLE
TDLibException cannot be resolved to a type

### ISSUE THREAD

**Issue by eos1d3** [tdlight-team/tdlight-java#22]
Using the following dependency and the example program, TDLibException cannot be resolved.

```
<dependency>
  <groupId>it.tdlight</groupId>
  <artifactId>tdlight-java</artifactId>
  <version>3.171.31</version>
</dependency>
<dependency>
  <groupId>it.tdlight</groupId>
  <artifactId>tdlight-natives-linux-amd64</artifactId>
  <version>3.2.31</version>
</dependency>
```

Is anything missing?

**Comment by Cavallium** [comment]
I updated the examples, they were outdated.
Also, use the latest version of tdlight java:

```xml
<dependency>
  <groupId>it.tdlight</groupId>
  <artifactId>tdlight-java</artifactId>
  <version>3.171.36</version>
</dependency>
<dependency>
  <groupId>it.tdlight</groupId>
  <artifactId>tdlight-natives-linux-amd64</artifactId>
  <version>3.2.48</version>
</dependency>
```

**Comment by eos1d3** [comment]
I test the example on Mac, so I use these:

```
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-java</artifactId>
	<version>3.171.36</version>
</dependency>
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlib-natives-osx-amd64</artifactId>
	<version>3.2.48</version>
</dependency>
```

But there is still error:

```
it.tdlight.common.utils.CantLoadLibrary: FATAL: Init failled when load tdlib library, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:88)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:66)
	at it.tdlight.common.Init.start(Init.java:44)
	at eos1d3.telegram_forwarder.App.main(App.java:13)
Caused by: java.io.IOException: Native libraries for platform osx-amd64 not found!
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:177)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:83)
	... 3 more
it.tdlight.common.utils.CantLoadLibrary: FATAL: Init failled when load tdlib library, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:88)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:66)
	at it.tdlight.common.Init.start(Init.java:44)
	at it.tdlight.common.InternalClientManager.<init>(InternalClientManager.java:19)
	at it.tdlight.common.InternalClientManager.lambda$get$0(InternalClientManager.java:28)
	at java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:179)
	at it.tdlight.common.InternalClientManager.get(InternalClientManager.java:28)
	at it.tdlight.common.CommonClientManager.getClientManager(CommonClientManager.java:9)
	at it.tdlight.common.CommonClientManager.create(CommonClientManager.java:16)
	at it.tdlight.tdlight.ClientManager.create(ClientManager.java:20)
	at eos1d3.telegram_forwarder.App.main(App.java:20)
Caused by: java.io.IOException: Native libraries for platform osx-amd64 not found!
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:177)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:83)
	... 10 more
Exception in thread "TDLib thread" java.lang.UnsatisfiedLinkError: it.tdlight.jni.NativeClient.nativeClientReceive([I[J[Lit/tdlight/jni/TdApi$Object;D)I
	at it.tdlight.jni.NativeClient.nativeClientReceive(Native Method)
	at it.tdlight.common.NativeClientAccess.receive(NativeClientAccess.java:22)
	at it.tdlight.common.ResponseReceiver.run(ResponseReceiver.java:54)

```

**Comment by andrew-ld** [comment]
Caused by: java.io.IOException: Native libraries for platform osx-amd64 not found!

**Comment by andrew-ld** [comment]
you should include 'tdlight-natives-osx-amd64' in your porject

**Comment by eos1d3** [comment]
I find 'tdlib-natives-osx-amd64-3.2.48.jar' is already in Eclipse project "Maven Dependencies" folder already. So...?

**Comment by Cavallium** [comment]
You aren't reading what you are writing. You are writing "tdlib", not "tdlight"...

**Comment by Cavallium** [comment]
use "**tdlight**-natives-osx-amd64'"

**Comment by eos1d3** [comment]
Just realised this. Thanks!

**Comment by eos1d3** [comment]
After fixing the name, it shows the same error above

```
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-natives-osx-amd64</artifactId>
	<version>3.2.48</version>
</dependency>

```

**Comment by Cavallium** [comment]
You are building it wrong, i don't know what you are doing but it must work

**Comment by Cavallium** [comment]
Does it work on linux?

**Comment by eos1d3** [comment]
I created a Maven project in Eclipse, then I just copy the Example, and include the following in pom.xml

```
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-natives-osx-amd64</artifactId>
	<version>3.2.48</version>
</dependency>
```

When I run it, it show "Init failled when load tdlib library, execution can't continue".

I can try to test on Windows later. I do not have linux to test.

**Comment by eos1d3** [comment]
In order to use on Windows, I change to `dlight-natives-windows-amd64`

```
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-java</artifactId>
	<version>3.171.36</version>
</dependency>
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-natives-windows-amd64</artifactId>
	<version>3.2.48</version>
</dependency>
		 
```


It shows the same compilation errors  on both Mac and Windows"

```
Failed to read artifact descriptor for it.tdlight:tdlight-natives-windows-amd64:jar:3.2.48
Missing artifact it.cavallium:concurrent-locks:jar:1.0.8	
Missing artifact it.tdlight:tdlight-api:jar:3.2.48
Missing artifact it.tdlight:tdlight-java:jar:3.171.36
Missing artifact it.tdlight:tdlight-natives-osx-amd64:jar:3.2.48
Missing artifact it.tdlight:tdlight-natives-windows-amd64:jar:3.2.48
Missing artifact it.unimi.dsi:fastutil:jar:8.3.1
Missing artifact junit:junit:jar:4.11
Missing artifact org.hamcrest:hamcrest-core:jar:1.3	pom.xml	
The container 'Maven Dependencies' references non existing library '/Users/xxx/.m2/repository/it/tdlight/tdlight-natives-windows-amd64/3.2.48/tdlight-natives-windows-amd64-3.2.48.jar'
The project cannot be built until build path errors are resolved
```

**Comment by Cavallium** [comment]
Did you add the repository?

**Comment by eos1d3** [comment]
Of course I do, see below.

During testing on Windows with Eclipse, if I use `tdlight-natives-osx-amd64`, there are no such compilation errors. After changing it to `tdlight-natives-windows-amd64`, the errors appear.

Then I did the same on Mac with `tdlight-natives-windows-amd64`, I see exactly the same error on Windows.

```xml
<properties>
	<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	<maven.compiler.source>1.8</maven.compiler.source>
	<maven.compiler.target>1.8</maven.compiler.target>
</properties>

<repositories>
<repository>
	<id>mchv</id>
	<name>MCHV Apache Maven Packages</name>
	<url>https://mvn.mchv.eu/repository/mchv/</url>
</repository>
</repositories>

<dependencies>
<dependency>
	<groupId>junit</groupId>
	<artifactId>junit</artifactId>
	<version>4.11</version>
	<scope>test</scope>
</dependency>

<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-java</artifactId>
	<version>3.171.36</version>
</dependency>
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-natives-osx-amd64</artifactId>
	<version>3.2.48</version>
</dependency>
<dependency>
	<groupId>it.tdlight</groupId>
	<artifactId>tdlight-natives-windows-amd64</artifactId>
	<version>3.2.48</version>
</dependency>

</dependencies>
```

**Comment by Cavallium** [comment]
That's strange, it should work...

**Comment by eos1d3** [comment]
Please note that whenever I use `tdlight-natives-windows-amd64` on both Mac and Windows, those are compilation error. I can't even run it.

**Comment by Cavallium** [comment]
I tried now and it works also with windows.
Try to delete .m2 cache folder, maybe your local maven repository is broken.

**Comment by eos1d3** [comment]
Removing .m2 is not enough, it needs to update Maven project as well.
Now I see these output on Windows. So it seems Windows version is working.

```
[ 3][t 0][1610818462.646162033][Client.cpp:276][&td_requests]	Begin to wait for updates with timeout 2.000000
[ 3][t 5][1610818462.653428792][Td.cpp:4621][#1][!Td][&td_requests]	Sending update: UpdateOption {
  name = "version"
  value = OptionValueString {
    value = "1.7.0"
  }
}
```

But doing the same (remove .m2 and update Maven) on Mac is having the same problem:
1. If I add `tdlight-natives-windows-amd64` on Mac, there are 8 compilation errors.
2. If I use only `tdlight-natives-osx-amd64`, it always gives `Init failled when load tdlib library, execution can't continue`

PS: How to login account or using TOKEN to login? I know how to do in TDLIB, but not this library.

Thanks a lot!

**Comment by Cavallium** [comment]
Login using phone number or token works the same as the original tdlib.

**Comment by eos1d3** [comment]
Hi, please check if it is openssl issue.

For TDLIB, I found that if openssl is not installed, there is an error `Library not loaded`.  And for the Mac I am using, it does not have it installed.

And for the error of this library on Mac, I am seeing:

`Caused by: java.lang.UnsatisfiedLinkError: /Users/xxx/eclipse-workspace/telegram-forwarder/.cache/version-tdlight-3.171.36-3.2.48/tdjni/tdjni.dylib: dlopen(/Users/xxx/eclipse-workspace/telegram-forwarder/.cache/version-tdlight-3.171.36-3.2.48/tdjni/tdjni.dylib, 1): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib`

**Comment by andrew-ld** [comment]
you must install libssl 1.1 on your operating system
