### ISSUE TITLE
no response after I entered correct verification code in console

### ISSUE THREAD

**Issue by crazysvn** [tdlight-team/tdlight-java#235]
the informations in console are as below:

[login] Do you want to login using a bot [token], a [phone] number, or a [qr] code? [token/phone/qr]: phone
[login] Please type your phone number: [login] Please type your phone number: xxx
[xxx] Enter authentication code
	Phone number: xxx
	Timeout: 0 seconds
	Code type: TelegramMessage:  55489

Closing...
Closed
Exception in thread "main" java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
	at telegram.login.Example.main(Example.java:80)

**Comment by crazysvn** [comment]
must be because I didn't use app id

**Comment by crazysvn** [comment]
after I set correct api_id and api_hash, still no response

**Comment by crazysvn** [comment]
turns out in it.tdlight.util.ScannerUtils the interruptibleReadLine(scanner) will read and return a blank line before verification code is entered. I use eclipse to run this app, not sure if such condition can happen in other IDE.
