### ISSUE TITLE
Cannot run the library

### ISSUE THREAD

**Issue by WolfAlm** [tdlight-team/tdlight-java#30]
When i added to maven:

```
  <dependencies>
    <dependency>
      <groupId>it.tdlight</groupId>
      <artifactId>tdlib-java</artifactId>
      <version>4.171.78</version>
    </dependency>
    <dependency>
      <groupId>it.tdlight</groupId>
      <artifactId>tdlib-natives-windows-amd64</artifactId>
      <version>3.3.14</version>
    </dependency>
  </dependencies>
```
And I run Example class - i got the issuse here. How to resolve it?

```
Exception in thread "main" it.tdlight.common.utils.CantLoadLibrary: FATAL: Init failled when load tdlib library, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:88)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:66)
	at it.tdlight.common.Init.start(Init.java:44)
	at Example.main(Example.java:300)
Caused by: java.io.IOException: Native libraries for platform win-amd64 not found!
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:177)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:83)
	... 3 more
```

**Comment by Cavallium** [comment]
@WolfAlm You forgot to use windows libraries. Please look at the README

**Comment by WolfAlm** [comment]
> @WolfAlm You forgot to use windows libraries. Please look at the README

but... 
![image](https://user-images.githubusercontent.com/60275667/112372598-0ee7a080-8cf1-11eb-8661-80395d7d200e.png)

**Comment by Cavallium** [comment]
Try to rebuild the project with maven

**Comment by WolfAlm** [comment]
I have just created new project and all works. Thanks

**Comment by Cavallium** [comment]
@WolfAlm good, you had to rebuild the project with maven
