### ISSUE TITLE
Can't load library in Spring Boot

### ISSUE THREAD

**Issue by WolfAlm** [tdlight-team/tdlight-java#34]
When i wrote Init.start() and built spring application, then i got exception:

```
[ 1][t 0][1620245307.392618656][tl_jni_object.cpp:38]	Can't find field [userId] with signature [I]
FATAL ERROR in native method: Can't find field [userId] with signature [I]
	at java.lang.ClassLoader$NativeLibrary.load0(java.base@11.0.8/Native Method)
	at java.lang.ClassLoader$NativeLibrary.load(java.base@11.0.8/ClassLoader.java:2430)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.8/ClassLoader.java:2487)
	- locked <0x0000000712b07658> (a java.util.HashSet)
	at java.lang.ClassLoader.loadLibrary0(java.base@11.0.8/ClassLoader.java:2684)
	at java.lang.ClassLoader.loadLibrary(java.base@11.0.8/ClassLoader.java:2617)
	at java.lang.Runtime.load0(java.base@11.0.8/Runtime.java:765)
	- locked <0x0000000712b07ab8> (a java.lang.Runtime)
	at java.lang.System.load(java.base@11.0.8/System.java:1835)
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:189)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:83)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:66)
	at it.tdlight.common.Init.start(Init.java:44)
	- locked <0x00000007122c46e8> (a java.lang.Class for it.tdlight.common.Init)
	at com.example.teeeest.TeeeestApplication.main(TeeeestApplication.java:12)
```

pom.xml

```
  <repositories>
    <repository>
      <id>mchv-release</id>
      <name>MCHV Release Apache Maven Packages</name>
      <url>https://mvn.mchv.eu/repository/mchv</url>
    </repository>
    <repository>
      <id>mchv-snapshot</id>
      <name>MCHV Snapshot Apache Maven Packages</name>
      <url>https://mvn.mchv.eu/repository/mchv-snapshot</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>it.tdlight</groupId>
      <artifactId>tdlight-java</artifactId>
      <version>4.171.110</version>
    </dependency>
    <dependency>
      <groupId>it.tdlight</groupId>
      <artifactId>tdlight-natives-windows-amd64</artifactId>
      <version>3.3.28</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
          .........
          ....
          ...
  <dependencies>
```

How to load Library in Application:

```
@SpringBootApplication
public class TeeeestApplication {

  static {
    try {
      Init.start();
    } catch (CantLoadLibrary cantLoadLibrary) {
      cantLoadLibrary.printStackTrace();
    }
  }

    public static void main(String[] args) throws CantLoadLibrary {
    SpringApplication.run(TeeeestApplication.class, args);
  }

}
```

This with any app, what to do?

**Comment by Cavallium** [comment]
@WolfAlm You used a wrong version of the library

**Comment by Cavallium** [comment]
@WolfAlm Please check that the natives and the main library are the same version as suggested here: https://github.com/tdlight-team/tdlight-java/releases/tag/v4.171.110

**Comment by WolfAlm** [comment]
> @WolfAlm Please check that the natives and the main library are the same version as suggested here: https://github.com/tdlight-team/tdlight-java/releases/tag/v4.171.110

I edited pom to correct version, and i got same exception :
![image](https://user-images.githubusercontent.com/60275667/117265260-ba415480-ae5c-11eb-8994-768131c609aa.png)

**Comment by Cavallium** [comment]
Please rebuild the project and delete the ".cache" folder where you executed the program
