### ISSUE TITLE
`GLIBC_2.29' not found

### ISSUE THREAD

**Issue by wind-hx** [tdlight-team/tdlight-java#47]
```
Exception in thread "main" it.tdlight.common.utils.CantLoadLibrary: FATAL: Init failled when load tdlib library, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:88)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:66)
	at it.tdlight.common.Init.start(Init.java:44)
	at com.wind.telegram.transport.Main.main(Main.java:75)
Caused by: java.lang.UnsatisfiedLinkError: /root/.cache/version-tdlight-1.7.7.0-3.3.129/tdjni/tdjni.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /root/.cache/version-tdlight-1.7.7.0-3.3.129/tdjni/tdjni.so)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
	at java.base/java.lang.Runtime.load0(Runtime.java:765)
	at java.base/java.lang.System.load(System.java:1835)
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:189)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:83)
	... 3 more

```

**Comment by wind-hx** [comment]
Can it be compiled with glibc2.28

**Comment by Cavallium** [comment]
Done

**Comment by leebuy** [comment]
Can it be compiled with glibc2.17?  thanks.

**Comment by cavallium** [comment]
> Can it be compiled with glibc2.17? thanks.

What OS are you using?
