### ISSUE TITLE
Can't find field [offsetOrder] with signature [J]

### ISSUE THREAD

**Issue by wind-hx** [tdlight-team/tdlight-java#48]
macos
artifactId:tdlight-java
version:1.7.7.0
artifactId:tdlight-natives-osx-amd64
version:3.3.129

init error

```
telegram-transport init...
[ 1][t 0][1632736701.648375034][tl_jni_object.cpp:39]	Can't find field [offsetOrder] with signature [J]
FATAL ERROR in native method: Can't find field [offsetOrder] with signature [J]
	at java.lang.ClassLoader$NativeLibrary.load0(java.base@11.0.10/Native Method)
	at java.lang.ClassLoader$NativeLibrary.load(java.base@11.0.10/ClassLoader.java:2430)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@11.0.10/ClassLoader.java:2487)
	- locked <0x000000070c337828> (a java.util.HashSet)
	at java.lang.ClassLoader.loadLibrary0(java.base@11.0.10/ClassLoader.java:2684)
	at java.lang.ClassLoader.loadLibrary(java.base@11.0.10/ClassLoader.java:2617)
	at java.lang.Runtime.load0(java.base@11.0.10/Runtime.java:765)
	- locked <0x00000007004d4ce0> (a java.lang.Runtime)
	at java.lang.System.load(java.base@11.0.10/System.java:1835)
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:189)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:83)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:66)
	at it.tdlight.common.Init.start(Init.java:44)
	- locked <0x000000070fedf9e8> (a java.lang.Class for it.tdlight.common.Init)
	at com.wind.telegram.transport.Main.main(Main.java:75)
Disconnected from the target VM, address: '127.0.0.1:62478', transport: 'socket'

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

```

**Comment by Cavallium** [comment]
Can you update to the latest major release that has just been released?

**Comment by wind-hx** [comment]
> Can you update to the latest major release that has just been released?

<dependency>
                <groupId>it.tdlight</groupId>
                <artifactId>tdlight-java</artifactId>
                <version>2.7.8.7</version>
            </dependency>
            <dependency>
                <groupId>it.tdlight</groupId>
                <artifactId>tdlight-natives-linux-amd64</artifactId>
                <version>3.3.149</version>
            </dependency>
            <dependency>
                <groupId>it.tdlight</groupId>
                <artifactId>tdlight-natives-osx-amd64</artifactId>
                <version>3.3.149</version>
            </dependency>

```
telegram-transport init...
Exception in thread "main" it.tdlight.common.utils.CantLoadLibrary: FATAL: Init failed when loading TDLib native libraries, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:91)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:67)
	at it.tdlight.common.Init.start(Init.java:44)
	at com.wind.telegram.transport.Main.main(Main.java:75)
Caused by: java.io.IOException: Native libraries for platform OSX-AMD64 not found!
	at it.tdlight.common.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:180)
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:86)
	... 3 more
```

**Comment by wind-hx** [comment]
```
<dependency>
                <groupId>it.tdlight</groupId>
                <artifactId>tdlight-java</artifactId>
                <version>2.7.8.7</version>
            </dependency>
            <dependency>
                <groupId>it.tdlight</groupId>
                <artifactId>tdlight-natives-linux-amd64</artifactId>
                <version>3.3.152</version>
            </dependency>
            <dependency>
                <groupId>it.tdlight</groupId>
                <artifactId>tdlight-natives-osx-amd64</artifactId>
                <version>3.3.152</version>
            </dependency>

The replace version is not error
```
