### ISSUE TITLE
Using Phone login gives exception while trying to parse the phone number

### ISSUE THREAD

**Issue by d3athwarrior** [tdlight-team/tdlight-java#53]
Hi,
I am using the [example file](https://github.com/tdlight-team/tdlight-java/blob/73d9d977ccb8edf240a1b33c3ca999ff53fd5a6f/example/src/main/java/it.tdlight.example/Example.java) and used phone login instead of QR code or Token login.

The code gives exception at the following line: 
https://github.com/tdlight-team/tdlight-java/blob/73d9d977ccb8edf240a1b33c3ca999ff53fd5a6f/src/main/java/it/tdlight/client/ConsoleInteractiveAuthenticationData.java#L101

```
java.lang.NumberFormatException: For input string: "4956485350545755535153"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Long.parseLong(Long.java:692)
	at java.base/java.lang.Long.parseLong(Long.java:817)
	at it.tdlight.client.ConsoleInteractiveAuthenticationData.initializeIfNeeded(ConsoleInteractiveAuthenticationData.java:101)
	at it.tdlight.client.ConsoleInteractiveAuthenticationData.askData(ConsoleInteractiveAuthenticationData.java:22)
	at it.tdlight.client.AuthorizationStateWaitAuthenticationDataHandler.onUpdate(AuthorizationStateWaitAuthenticationDataHandler.java:38)
	at it.tdlight.client.AuthorizationStateWaitAuthenticationDataHandler.onUpdate(AuthorizationStateWaitAuthenticationDataHandler.java:17)
	at it.tdlight.client.SimpleTelegramClient.lambda$addUpdateHandler$1(SimpleTelegramClient.java:145)
	at it.tdlight.client.SimpleTelegramClient.handleUpdate(SimpleTelegramClient.java:91)
	at it.tdlight.common.internal.InternalClient.handleResponse(InternalClient.java:106)
	at it.tdlight.common.internal.InternalClient.handleEvent(InternalClient.java:122)
	at it.tdlight.common.internal.InternalClient.handleEvents(InternalClient.java:75)
	at it.tdlight.common.internal.InternalClientManager.handleClientEvents(InternalClientManager.java:80)
	at it.tdlight.common.internal.ResponseReceiver.run(ResponseReceiver.java:107)
```

Your number parsing logic needs updating.

Why not simply do a `Long.parseLong()`?

**Comment by d3athwarrior** [comment]
Hey that is fine, even I am a developer, I understand these things happen.

[Here is an example](https://onecompiler.com/java/3xew59gf8) of your exact code being run online with perfectly valid input and it returns the value that you see in the above exception if you just click on the Run button to execute the code.

If at all this matters then I am using JDK 11 on my local which is same as the site that I have shared the link of.
