### ISSUE TITLE
Load dynamic library failed on macOS

### ISSUE THREAD

**Issue by AiziChen** [tdlight-team/tdlight-java#57]
version information:
tdlight-java: v2.7.8.32
tdlight-natives-osx-amd64: v4.0.173

I already install `openssl@1.1` and linked it to `/usr/local/opt/openssl` directory.

The Exception trace here:

```
Exception in thread "main" it.tdlight.common.utils.CantLoadLibrary: Init failed when loading TDLib native libraries, execution can't continue
	at it.tdlight.common.utils.LoadLibrary.loadLibrary(LoadLibrary.java:93)
	at it.tdlight.common.utils.LoadLibrary.load(LoadLibrary.java:71)
	at it.tdlight.common.Init.start(Init.java:44)
	at Main.main(Main.java:18)
Caused by: java.lang.UnsatisfiedLinkError: /Users/coq/IdeaProjects/telegram-msg/.cache/version-tdlight-2.7.8.32-4.0.173/tdjni/tdjni.dylib: dlopen(/Users/coq/IdeaProjects/telegram-msg/.cache/version-tdlight-2.7.8.32-4.0.173/tdjni/tdjni.dylib, 1): Library not loaded: /usr/local/opt/openssl@3/lib/libcrypto.3.dylib
  Referenced from: /Users/coq/IdeaProjects/telegram-msg/.cache/version-tdlight-2.7.8.32-4.0.173/tdjni/tdjni.dylib
  Reason: image not found
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:383)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:227)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:169)

```

**Comment by Cavallium** [comment]
try with openssl@3

**Comment by AiziChen** [comment]
@Cavallium 
It works, Thank you so much!
