### ISSUE TITLE
RegisterNatives failed for nativeClientReceive with signature (J[J[Lit/tdlight/tdlib/TdApi$Object;DZZ)I

### ISSUE THREAD

**Issue by ashvydkyi** [tdlight-team/tdlight-java#6]
hey guys,

while running `tdlib-java` on macOS the following exception is thrown

```
FATAL ERROR in native method: RegisterNatives failed for nativeClientReceive with signature (J[J[Lit/tdlight/tdlib/TdApi$Object;DZZ)I
	at java.lang.ClassLoader$NativeLibrary.load0(java.base@14.0.2/Native Method)
	at java.lang.ClassLoader$NativeLibrary.load(java.base@14.0.2/ClassLoader.java:2452)
	at java.lang.ClassLoader$NativeLibrary.loadLibrary(java.base@14.0.2/ClassLoader.java:2508)
	- locked <0x0000000700432650> (a java.util.HashSet)
	at java.lang.ClassLoader.loadLibrary0(java.base@14.0.2/ClassLoader.java:2704)
	at java.lang.ClassLoader.loadLibrary(java.base@14.0.2/ClassLoader.java:2637)
	at java.lang.Runtime.load0(java.base@14.0.2/Runtime.java:745)
	at java.lang.System.load(java.base@14.0.2/System.java:1871)
	at it.tdlight.tdlight.utils.LoadLibrary.loadJarLibrary(LoadLibrary.java:134)
	at it.tdlight.tdlight.utils.LoadLibrary.loadLibrary(LoadLibrary.java:80)
	at it.tdlight.tdlight.utils.LoadLibrary.load(LoadLibrary.java:63)
	at it.tdlight.tdlight.Init.start(Init.java:46)
	- locked <0x00000007032c9558> (a java.lang.Class for it.tdlight.tdlight.Init)
	at it.tdlight.tdlight.Client.<init>(Client.java:31)
[ 1][t 0][1599679723.491142034][tl_jni_object.cpp:37]	RegisterNatives failed for nativeClientReceive with signature (J[J[Lit/tdlight/tdlib/TdApi$Object;DZZ)I
```

```
<dependency>
   <groupId>it.tdlight</groupId>
   <artifactId>tdlib-java</artifactId>
   <version>3.168.11</version>
</dependency>
```

**Comment by ashvydkyi** [comment]
.JTDLibLibraries contains incorrect dynamic library.
